PRODUCT_VERSION_MAJOR = 23
PRODUCT_VERSION_MINOR = 2

# Edition: Professional (Sc₂O₃) | Casual (Sc) [default] | Academy (ScF₃)
SCANDIUM_EDITION ?= Casual

ifeq ($(SCANDIUM_EDITION),Professional)
    SCANDIUM_EDITION_CODENAME := Sc2O3
else ifeq ($(SCANDIUM_EDITION),Academy)
    SCANDIUM_EDITION_CODENAME := ScF3
else
    override SCANDIUM_EDITION := Casual
    SCANDIUM_EDITION_CODENAME := Sc
endif

SCANDIUM_EDITION_LOWER := $(shell echo $(SCANDIUM_EDITION) | tr 'A-Z' 'a-z')

ifeq ($(SCANDIUM_VERSION_APPEND_TIME_OF_DAY),true)
    SCANDIUM_BUILD_DATE := $(shell date -u +%Y%m%d_%H%M%S)
else
    SCANDIUM_BUILD_DATE := $(shell date -u +%Y%m%d)
endif

SCANDIUM_BUILD_TIMESTAMP := $(shell date -u +%s)

ifndef SCANDIUM_BUILDTYPE
    ifdef RELEASE_TYPE
        SCANDIUM_BUILDTYPE := $(shell echo $(RELEASE_TYPE) | sed -e 's|^SCANDIUM_||g')
    endif
endif

ifeq ($(filter COOKIE SNAPSHOT EXPERIMENTAL,$(SCANDIUM_BUILDTYPE)),)
    SCANDIUM_BUILDTYPE := COOKIE
    SCANDIUM_EXTRAVERSION :=
endif

ifeq ($(SCANDIUM_BUILDTYPE), COOKIE)
    ifneq ($(TARGET_UNOFFICIAL_BUILD_ID),)
        SCANDIUM_EXTRAVERSION := -$(TARGET_UNOFFICIAL_BUILD_ID)
    endif
endif

SCANDIUM_VERSION_SUFFIX := $(SCANDIUM_BUILD_DATE)-$(SCANDIUM_BUILDTYPE)$(SCANDIUM_EXTRAVERSION)-$(SCANDIUM_BUILD)
SCANDIUM_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(SCANDIUM_VERSION_SUFFIX)
SCANDIUM_DISPLAY_VERSION := ScandiumUI $(PRODUCT_VERSION_MAJOR) $(SCANDIUM_EDITION) — $(SCANDIUM_VERSION_SUFFIX)
SCANDIUM_FINGERPRINT := scandiumui/$(SCANDIUM_EDITION_LOWER)/$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)/$(SCANDIUM_BUILD_DATE)/$(SCANDIUM_BUILDTYPE)

PRODUCT_PRODUCT_PROPERTIES += \
    ro.scandium.version=$(SCANDIUM_VERSION) \
    ro.scandium.display.version=$(SCANDIUM_DISPLAY_VERSION) \
    ro.scandium.build.version=$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR) \
    ro.scandium.releasetype=$(SCANDIUM_BUILDTYPE) \
    ro.scandium.edition=$(SCANDIUM_EDITION_LOWER) \
    ro.scandium.edition.codename=$(SCANDIUM_EDITION_CODENAME) \
    ro.scandium.build.date=$(SCANDIUM_BUILD_DATE) \
    ro.scandium.build.timestamp=$(SCANDIUM_BUILD_TIMESTAMP) \
    ro.scandium.fingerprint=$(SCANDIUM_FINGERPRINT)
